---
- name: Install web server
  apt: 
      name: "apache2"  
      state: present
      update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: copier index dans la zone de destination
  template:
      src: index.html.j2
      dest: /var/www/html/index.html
  notify:
      - Restart Apache

- name: Démarrage du service apache if not started
  service:
    name: apache2
    state: started
    enabled: true
