---
- hosts: webserver
  remote_user: root
  vars_files:
    - "../vars/{{env}}_vars.yml"
    - "../vars/{{env}}_vault.yml"
  tasks:
    - name: "Ajout d'utilisateurs"
      user:
        name: "{{username}}"
        password: "{{password | password_hash('sha512')}}"
        uid: 1234
